-- Extensão complementar do pacote wildlife para cobrir inspeções, carcaças,
-- gestão ambiental/ASA, comunicações externas, treinamentos e KPIs BAIST.
-- Executar após aplicar wildlife_full_package.sql.

BEGIN;

SET search_path = wildlife, public;

-------------------------------------------------------------------------------
-- Inspeções de sítio/ASA
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fact_inspection (
  inspection_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  airport_id         BIGINT NOT NULL REFERENCES airport(airport_id) ON DELETE CASCADE,
  inspection_type    TEXT NOT NULL CHECK (inspection_type IN ('site','asa')),
  date_utc           DATE NOT NULL,
  start_time         TIME,
  end_time           TIME,
  team_name          TEXT,
  weather_summary    TEXT,
  route_summary      TEXT,
  grid_refs          TEXT[] DEFAULT '{}',
  reported_by_user_id BIGINT REFERENCES app_user(user_id),
  reported_by_name   TEXT,
  notes              TEXT,
  observations       JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_fact_inspection_air_type_date
  ON fact_inspection (airport_id, inspection_type, date_utc DESC);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_fact_inspection_upd') THEN
    CREATE TRIGGER trg_fact_inspection_upd
      BEFORE UPDATE ON fact_inspection
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

-------------------------------------------------------------------------------
-- Registro de carcaças recolhidas
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fact_carcass (
  carcass_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  airport_id         BIGINT NOT NULL REFERENCES airport(airport_id) ON DELETE CASCADE,
  date_utc           DATE NOT NULL,
  time_local         TIME,
  location_id        BIGINT REFERENCES dim_location(location_id) ON DELETE SET NULL,
  quadrant           TEXT,
  latitude_dec       NUMERIC(9,6),
  longitude_dec      NUMERIC(9,6),
  species_id         BIGINT REFERENCES dim_species(species_id),
  species_guess      TEXT,
  quantity           INTEGER CHECK (quantity IS NULL OR quantity >= 1),
  mass_grams         NUMERIC(10,2) CHECK (mass_grams IS NULL OR mass_grams >= 0),
  photo_url          TEXT,
  dna_collected      BOOLEAN,
  storage_method     TEXT,
  destination        TEXT CHECK (destination IS NULL OR destination IN ('aterro','autoclave','incineracao','outro')),
  destination_detail TEXT,
  handled_by         TEXT,
  bag_tag            TEXT,
  notified_sigra     BOOLEAN,
  notes              TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_fact_carcass_air_date
  ON fact_carcass (airport_id, date_utc DESC);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_fact_carcass_upd') THEN
    CREATE TRIGGER trg_fact_carcass_upd
      BEFORE UPDATE ON fact_carcass
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

-------------------------------------------------------------------------------
-- Auditorias ambientais (resíduos, esgoto, sistema de proteção etc.)
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fact_environment_audit (
  audit_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  airport_id         BIGINT NOT NULL REFERENCES airport(airport_id) ON DELETE CASCADE,
  date_utc           DATE NOT NULL,
  category           TEXT NOT NULL CHECK (category IN ('residuos','esgoto','sistema_protecao','foco_secundario','outro')),
  area_reference     TEXT,
  status             TEXT CHECK (status IS NULL OR status IN ('pendente','em_execucao','resolvido')),
  findings           TEXT,
  actions_planned    TEXT,
  responsible_party  TEXT,
  follow_up_date     DATE,
  attachments        JSONB DEFAULT '[]'::jsonb,
  notes              TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_fact_environment_audit_air_cat_date
  ON fact_environment_audit (airport_id, category, date_utc DESC);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_fact_environment_audit_upd') THEN
    CREATE TRIGGER trg_fact_environment_audit_upd
      BEFORE UPDATE ON fact_environment_audit
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

-------------------------------------------------------------------------------
-- Focos atrativos na ASA
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fact_asa_focus (
  asa_focus_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  airport_id         BIGINT NOT NULL REFERENCES airport(airport_id) ON DELETE CASCADE,
  municipality       TEXT,
  focus_type         TEXT,
  description        TEXT,
  latitude_dec       NUMERIC(9,6),
  longitude_dec      NUMERIC(9,6),
  distance_km        NUMERIC(8,2) CHECK (distance_km IS NULL OR distance_km >= 0),
  status             TEXT CHECK (status IS NULL OR status IN ('monitorado','em_gestao','mitigado')),
  responsible_org    TEXT,
  notified_at        DATE,
  next_follow_up     DATE,
  protocol_ref       TEXT,
  notes              TEXT,
  attachments        JSONB DEFAULT '[]'::jsonb,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_fact_asa_focus_air_status
  ON fact_asa_focus (airport_id, status);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_fact_asa_focus_upd') THEN
    CREATE TRIGGER trg_fact_asa_focus_upd
      BEFORE UPDATE ON fact_asa_focus
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

-------------------------------------------------------------------------------
-- Comunicações e ofícios externos
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fact_external_notice (
  notice_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  airport_id         BIGINT NOT NULL REFERENCES airport(airport_id) ON DELETE CASCADE,
  asa_focus_id       BIGINT REFERENCES fact_asa_focus(asa_focus_id) ON DELETE SET NULL,
  target_entity      TEXT NOT NULL,
  subject            TEXT,
  protocol_code      TEXT,
  status             TEXT CHECK (status IS NULL OR status IN ('enviado','em_andamento','respondido','encerrado')),
  sent_at            DATE,
  response_due_at    DATE,
  response_received_at DATE,
  notes              TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_fact_external_notice_air_status
  ON fact_external_notice (airport_id, status);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_fact_external_notice_upd') THEN
    CREATE TRIGGER trg_fact_external_notice_upd
      BEFORE UPDATE ON fact_external_notice
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

-------------------------------------------------------------------------------
-- Programas de treinamento
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fact_training_session (
  training_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  airport_id         BIGINT NOT NULL REFERENCES airport(airport_id) ON DELETE CASCADE,
  title              TEXT NOT NULL,
  audience           TEXT,
  start_date         DATE NOT NULL,
  end_date           DATE,
  hours_total        NUMERIC(6,2) CHECK (hours_total IS NULL OR hours_total >= 0),
  delivery_mode      TEXT,
  instructor         TEXT,
  topics             TEXT[] DEFAULT '{}',
  participants       JSONB DEFAULT '[]'::jsonb,
  materials_url      TEXT,
  notes              TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_fact_training_session_air_date
  ON fact_training_session (airport_id, start_date DESC);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_fact_training_session_upd') THEN
    CREATE TRIGGER trg_fact_training_session_upd
      BEFORE UPDATE ON fact_training_session
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

-------------------------------------------------------------------------------
-- Função de indicadores BAIST
-------------------------------------------------------------------------------
SET search_path = wildlife_kpi, public, wildlife;

CREATE OR REPLACE FUNCTION fn_baist_indicadores(
  p_inicio DATE,
  p_fim    DATE,
  p_airport_id BIGINT DEFAULT NULL
)
RETURNS TABLE (
  airport_id BIGINT,
  icao_code TEXT,
  airport_name TEXT,
  movimentos NUMERIC,
  reavi_10k NUMERIC,
  reasa_10k NUMERIC,
  reavi_com_dano_pct NUMERIC,
  refau_10k NUMERIC,
  peavi_por_movimento NUMERIC,
  pefau_por_movimento NUMERIC,
  sr10k NUMERIC,
  pct_colisoes_multiplas NUMERIC,
  massa_media_kg NUMERIC
) STABLE AS $$
  WITH periodo AS (
    SELECT p_inicio AS ini, p_fim AS fim
  ),
  mov AS (
    SELECT m.airport_id, SUM(m.movements)::numeric AS movimentos
    FROM wildlife_kpi.v_movements_daily m, periodo p
    WHERE m.day BETWEEN p.ini AND p.fim
    GROUP BY m.airport_id
  ),
  strikes AS (
    SELECT s.airport_id,
           COUNT(*) FILTER (WHERE s.event_type = 'colisao_ave' AND COALESCE(s.inside_aerodrome, TRUE)) AS col_aves_site,
           COUNT(*) FILTER (WHERE s.event_type = 'colisao_ave' AND COALESCE(s.inside_aerodrome, FALSE) = FALSE) AS col_aves_asa,
           COUNT(*) FILTER (WHERE s.event_type = 'colisao_ave' AND s.damage_id IS NOT NULL AND COALESCE(s.inside_aerodrome, TRUE)) AS col_aves_site_dano,
           COUNT(*) FILTER (WHERE s.event_type = 'colisao_outro_animal') AS col_outros,
           COUNT(*) FILTER (WHERE s.event_type IN ('colisao_ave','colisao_outro_animal')) AS col_totais,
           COUNT(*) FILTER (WHERE COALESCE(s.quantity,1) > 1) AS col_multiplas,
           SUM(sp.mass_grams * COALESCE(s.quantity,1)) FILTER (WHERE sp.mass_grams IS NOT NULL)::numeric AS massa_total_grams
    FROM wildlife.fact_strike s
    LEFT JOIN wildlife.dim_species sp ON sp.species_id = s.species_id
    JOIN periodo p ON s.date_utc BETWEEN p.ini AND p.fim
    GROUP BY s.airport_id
  ),
  quase AS (
    SELECT s.airport_id, COUNT(*) AS quase_aves
    FROM wildlife.fact_strike s
    JOIN periodo p ON s.date_utc BETWEEN p.ini AND p.fim
    WHERE s.event_type = 'quase_colisao'
    GROUP BY s.airport_id
  ),
  avist AS (
    SELECT s.airport_id,
           COUNT(*) FILTER (WHERE tg.name = 'Aves') AS avist_aves,
           COUNT(*) FILTER (WHERE tg.name IS NULL OR tg.name <> 'Aves') AS avist_fauna
    FROM wildlife.fact_sighting s
    LEFT JOIN wildlife.fact_sighting_item si ON si.sighting_id = s.sighting_id
    LEFT JOIN wildlife.dim_species sp ON sp.species_id = si.species_id
    LEFT JOIN wildlife.lu_taxon_group tg ON tg.group_id = sp.group_id
    JOIN periodo p ON s.date_utc BETWEEN p.ini AND p.fim
    GROUP BY s.airport_id
  )
  SELECT
    a.airport_id,
    a.icao_code,
    a.name,
    mov.movimentos,
    CASE WHEN mov.movimentos > 0 THEN ROUND(COALESCE(str.col_aves_site,0)::numeric / mov.movimentos * 10000, 4) ELSE NULL END AS reavi_10k,
    CASE WHEN mov.movimentos > 0 THEN ROUND(COALESCE(str.col_aves_asa,0)::numeric / mov.movimentos * 10000, 4) ELSE NULL END AS reasa_10k,
    CASE WHEN COALESCE(str.col_aves_site,0) > 0 THEN ROUND(str.col_aves_site_dano::numeric / NULLIF(str.col_aves_site,0) * 100, 2) ELSE NULL END AS reavi_com_dano_pct,
    CASE WHEN mov.movimentos > 0 THEN ROUND(COALESCE(str.col_outros,0)::numeric / mov.movimentos * 10000, 4) ELSE NULL END AS refau_10k,
    CASE WHEN mov.movimentos > 0 THEN ROUND((COALESCE(avist.avist_aves,0) + COALESCE(quase.quase_aves,0))::numeric / mov.movimentos, 4) ELSE NULL END AS peavi_por_movimento,
    CASE WHEN mov.movimentos > 0 THEN ROUND(COALESCE(avist.avist_fauna,0)::numeric / mov.movimentos, 4) ELSE NULL END AS pefau_por_movimento,
    CASE WHEN mov.movimentos > 0 THEN ROUND(COALESCE(str.col_totais,0)::numeric / mov.movimentos * 10000, 4) ELSE NULL END AS sr10k,
    CASE WHEN COALESCE(str.col_totais,0) > 0 THEN ROUND(COALESCE(str.col_multiplas,0)::numeric / str.col_totais * 100, 2) ELSE NULL END AS pct_colisoes_multiplas,
    CASE WHEN COALESCE(str.col_totais,0) > 0 THEN ROUND(COALESCE(str.massa_total_grams,0)::numeric / str.col_totais / 1000, 3) ELSE NULL END AS massa_media_kg
  FROM wildlife.airport a
  LEFT JOIN mov ON mov.airport_id = a.airport_id
  LEFT JOIN strikes str ON str.airport_id = a.airport_id
  LEFT JOIN quase ON quase.airport_id = a.airport_id
  LEFT JOIN avist ON avist.airport_id = a.airport_id
  WHERE p_airport_id IS NULL OR a.airport_id = p_airport_id
  ORDER BY a.name;
$$ LANGUAGE SQL;

COMMIT;
