-- Extensão complementar do pacote wildlife para cobrir inspeções, carcaças,
-- gestão ambiental/ASA, comunicações externas, treinamentos e KPIs BAIST.
-- Executar após aplicar wildlife_full_package.sql.

BEGIN;

SET search_path = wildlife, public;

-------------------------------------------------------------------------------
-- Quadrantes operacionais
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lu_quadrant (
  quadrant_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_quadrant_upd') THEN
    CREATE TRIGGER trg_quadrant_upd
      BEFORE UPDATE ON lu_quadrant
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

INSERT INTO lu_quadrant (code, description) VALUES
  ('N','Norte'),
  ('NE','Nordeste'),
  ('E','Leste'),
  ('SE','Sudeste'),
  ('S','Sul'),
  ('SW','Sudoeste'),
  ('W','Oeste'),
  ('NW','Noroeste'),
  ('C','Centro')
ON CONFLICT (code) DO UPDATE SET description=EXCLUDED.description;
-------------------------------------------------------------------------------
-- Catalogo de aeronaves operadas no Brasil
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lu_aircraft_model (
  aircraft_model_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  manufacturer      TEXT NOT NULL,
  model             TEXT NOT NULL,
  nickname          TEXT,
  category          TEXT,
  engine_type_id    SMALLINT REFERENCES lu_aircraft_engine_type(engine_type_id),
  wingspan_m        NUMERIC(6,2),
  length_m          NUMERIC(6,2),
  height_m          NUMERIC(5,2),
  seating_capacity  SMALLINT,
  mtow_kg           NUMERIC(8,1),
  notes             TEXT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (manufacturer, model)
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_aircraft_model_upd') THEN
    CREATE TRIGGER trg_aircraft_model_upd
      BEFORE UPDATE ON lu_aircraft_model
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

INSERT INTO lu_aircraft_model (manufacturer, model, nickname, category, engine_type_id, wingspan_m, length_m, height_m, seating_capacity, mtow_kg, notes)
VALUES
  ('Embraer', 'E195-E2', NULL, 'jato regional',
    (SELECT engine_type_id FROM lu_aircraft_engine_type WHERE name ILIKE 'turbofan%' ORDER BY engine_type_id LIMIT 1),
    35.10, 41.50, 10.90, 146, 62500, 'Azul/Voepass'),
  ('Airbus', 'A320neo', NULL, 'narrowbody',
    (SELECT engine_type_id FROM lu_aircraft_engine_type WHERE name ILIKE 'turbofan%' ORDER BY engine_type_id LIMIT 1),
    35.80, 37.60, 11.80, 186, 79000, 'LATAM/GOL/Azul'),
  ('Boeing', '737-800', NULL, 'narrowbody',
    (SELECT engine_type_id FROM lu_aircraft_engine_type WHERE name ILIKE 'turbofan%' ORDER BY engine_type_id LIMIT 1),
    35.80, 39.50, 12.50, 189, 79015, 'Frota predominante GOL'),
  ('ATR', '72-600', NULL, 'turboelice regional',
    (SELECT engine_type_id FROM lu_aircraft_engine_type WHERE name ILIKE 'turbo%lice%' ORDER BY engine_type_id LIMIT 1),
    27.10, 27.20, 7.60, 70, 23000, 'Operado pela Azul Conecta'),
  ('Cessna', '208 Caravan', NULL, 'utilitario',
    (SELECT engine_type_id FROM lu_aircraft_engine_type WHERE name ILIKE 'turbo%lice%' ORDER BY engine_type_id LIMIT 1),
    15.90, 12.70, 4.60, 9, 3970, 'Uso em taxi aéreo e cargas'),
  ('Sikorsky', 'S-76C', NULL, 'helicoptero',
    (SELECT engine_type_id FROM lu_aircraft_engine_type WHERE name ILIKE 'helic%' ORDER BY engine_type_id LIMIT 1),
    13.40, 13.00, 4.40, 12, 5300, 'Operacoes offshore'),
  ('Embraer', 'Phenom 300E', NULL, 'jato executivo',
    (SELECT engine_type_id FROM lu_aircraft_engine_type WHERE name ILIKE 'turbofan%' ORDER BY engine_type_id LIMIT 1),
    16.20, 15.90, 5.10, 10, 7950, 'Categoria business jet')
ON CONFLICT (manufacturer, model) DO UPDATE
SET category=EXCLUDED.category,
    engine_type_id=EXCLUDED.engine_type_id,
    wingspan_m=EXCLUDED.wingspan_m,
    length_m=EXCLUDED.length_m,
    height_m=EXCLUDED.height_m,
    seating_capacity=EXCLUDED.seating_capacity,
    mtow_kg=EXCLUDED.mtow_kg,
    notes=EXCLUDED.notes;

ALTER TABLE fact_strike
  ADD COLUMN IF NOT EXISTS aircraft_model_id BIGINT REFERENCES lu_aircraft_model(aircraft_model_id);

CREATE INDEX IF NOT EXISTS idx_fact_strike_aircraft_model ON fact_strike(aircraft_model_id);


-------------------------------------------------------------------------------
-- Inspeções de sítio/ASA
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fact_inspection (
  inspection_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  airport_id         BIGINT NOT NULL REFERENCES airport(airport_id) ON DELETE CASCADE,
  inspection_type    TEXT NOT NULL CHECK (inspection_type IN ('site','asa')),
  date_utc           DATE NOT NULL,
  start_time         TIME,
  end_time           TIME,
  team_name          TEXT,
  weather_summary    TEXT,
  route_summary      TEXT,
  grid_refs          TEXT[] DEFAULT '{}',
  reported_by_user_id BIGINT REFERENCES app_user(user_id),
  reported_by_name   TEXT,
  notes              TEXT,
  observations       JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_fact_inspection_air_type_date
  ON fact_inspection (airport_id, inspection_type, date_utc DESC);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_fact_inspection_upd') THEN
    CREATE TRIGGER trg_fact_inspection_upd
      BEFORE UPDATE ON fact_inspection
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

-------------------------------------------------------------------------------
-- Registro de carcaças recolhidas
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fact_carcass (
  carcass_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  airport_id         BIGINT NOT NULL REFERENCES airport(airport_id) ON DELETE CASCADE,
  date_utc           DATE NOT NULL,
  time_local         TIME,
  location_id        BIGINT REFERENCES dim_location(location_id) ON DELETE SET NULL,
  quadrant           TEXT,
  latitude_dec       NUMERIC(9,6),
  longitude_dec      NUMERIC(9,6),
  species_id         BIGINT REFERENCES dim_species(species_id),
  species_guess      TEXT,
  quantity           INTEGER CHECK (quantity IS NULL OR quantity >= 1),
  mass_grams         NUMERIC(10,2) CHECK (mass_grams IS NULL OR mass_grams >= 0),
  photo_url          TEXT,
  dna_collected      BOOLEAN,
  storage_method     TEXT,
  destination        TEXT CHECK (destination IS NULL OR destination IN ('aterro','autoclave','incineracao','outro')),
  destination_detail TEXT,
  handled_by         TEXT,
  bag_tag            TEXT,
  notified_sigra     BOOLEAN,
  notes              TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_fact_carcass_air_date
  ON fact_carcass (airport_id, date_utc DESC);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_fact_carcass_upd') THEN
    CREATE TRIGGER trg_fact_carcass_upd
      BEFORE UPDATE ON fact_carcass
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

-------------------------------------------------------------------------------
-- Auditorias ambientais (resíduos, esgoto, sistema de proteção etc.)
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fact_environment_audit (
  audit_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  airport_id         BIGINT NOT NULL REFERENCES airport(airport_id) ON DELETE CASCADE,
  date_utc           DATE NOT NULL,
  category           TEXT NOT NULL CHECK (category IN ('residuos','esgoto','sistema_protecao','foco_secundario','outro')),
  area_reference     TEXT,
  status             TEXT CHECK (status IS NULL OR status IN ('pendente','em_execucao','resolvido')),
  findings           TEXT,
  actions_planned    TEXT,
  responsible_party  TEXT,
  follow_up_date     DATE,
  attachments        JSONB DEFAULT '[]'::jsonb,
  notes              TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_fact_environment_audit_air_cat_date
  ON fact_environment_audit (airport_id, category, date_utc DESC);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_fact_environment_audit_upd') THEN
    CREATE TRIGGER trg_fact_environment_audit_upd
      BEFORE UPDATE ON fact_environment_audit
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

-------------------------------------------------------------------------------
-- Focos atrativos na ASA
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fact_asa_focus (
  asa_focus_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  airport_id         BIGINT NOT NULL REFERENCES airport(airport_id) ON DELETE CASCADE,
  municipality       TEXT,
  focus_type         TEXT,
  description        TEXT,
  latitude_dec       NUMERIC(9,6),
  longitude_dec      NUMERIC(9,6),
  distance_km        NUMERIC(8,2) CHECK (distance_km IS NULL OR distance_km >= 0),
  status             TEXT CHECK (status IS NULL OR status IN ('monitorado','em_gestao','mitigado')),
  responsible_org    TEXT,
  notified_at        DATE,
  next_follow_up     DATE,
  protocol_ref       TEXT,
  notes              TEXT,
  attachments        JSONB DEFAULT '[]'::jsonb,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_fact_asa_focus_air_status
  ON fact_asa_focus (airport_id, status);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_fact_asa_focus_upd') THEN
    CREATE TRIGGER trg_fact_asa_focus_upd
      BEFORE UPDATE ON fact_asa_focus
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

-------------------------------------------------------------------------------
-- Comunicações e ofícios externos
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fact_external_notice (
  notice_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  airport_id         BIGINT NOT NULL REFERENCES airport(airport_id) ON DELETE CASCADE,
  asa_focus_id       BIGINT REFERENCES fact_asa_focus(asa_focus_id) ON DELETE SET NULL,
  target_entity      TEXT NOT NULL,
  subject            TEXT,
  protocol_code      TEXT,
  status             TEXT CHECK (status IS NULL OR status IN ('enviado','em_andamento','respondido','encerrado')),
  sent_at            DATE,
  response_due_at    DATE,
  response_received_at DATE,
  notes              TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_fact_external_notice_air_status
  ON fact_external_notice (airport_id, status);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_fact_external_notice_upd') THEN
    CREATE TRIGGER trg_fact_external_notice_upd
      BEFORE UPDATE ON fact_external_notice
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS fact_external_notice_file (
  file_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notice_id   BIGINT NOT NULL REFERENCES fact_external_notice(notice_id) ON DELETE CASCADE,
  filename    TEXT NOT NULL,
  mime_type   TEXT NOT NULL CHECK (mime_type IN ('application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document')),
  file_size   BIGINT NOT NULL CHECK (file_size > 0),
  file_data   BYTEA NOT NULL,
  uploaded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_external_notice_file_notice
  ON fact_external_notice_file (notice_id);

-------------------------------------------------------------------------------
-- Programas de treinamento
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fact_training_session (
  training_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  airport_id         BIGINT NOT NULL REFERENCES airport(airport_id) ON DELETE CASCADE,
  title              TEXT NOT NULL,
  audience           TEXT,
  start_date         DATE NOT NULL,
  end_date           DATE,
  hours_total        NUMERIC(6,2) CHECK (hours_total IS NULL OR hours_total >= 0),
  delivery_mode      TEXT,
  instructor         TEXT,
  topics             TEXT[] DEFAULT '{}',
  participants       JSONB DEFAULT '[]'::jsonb,
  materials_url      TEXT,
  notes              TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_fact_training_session_air_date
  ON fact_training_session (airport_id, start_date DESC);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_fact_training_session_upd') THEN
    CREATE TRIGGER trg_fact_training_session_upd
      BEFORE UPDATE ON fact_training_session
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

-------------------------------------------------------------------------------
-- Função de indicadores BAIST
-------------------------------------------------------------------------------
SET search_path = wildlife_kpi, public, wildlife;

CREATE OR REPLACE FUNCTION fn_baist_indicadores(
  p_inicio DATE,
  p_fim    DATE,
  p_airport_id BIGINT DEFAULT NULL
)
RETURNS TABLE (
  airport_id BIGINT,
  icao_code TEXT,
  airport_name TEXT,
  movimentos NUMERIC,
  reavi_10k NUMERIC,
  reasa_10k NUMERIC,
  reavi_com_dano_pct NUMERIC,
  refau_10k NUMERIC,
  peavi_por_movimento NUMERIC,
  pefau_por_movimento NUMERIC,
  sr10k NUMERIC,
  pct_colisoes_multiplas NUMERIC,
  massa_media_kg NUMERIC
) STABLE AS $$
  WITH periodo AS (
    SELECT p_inicio AS ini, p_fim AS fim
  ),
  mov AS (
    SELECT m.airport_id, SUM(m.movements)::numeric AS movimentos
    FROM wildlife_kpi.v_movements_daily m, periodo p
    WHERE m.day BETWEEN p.ini AND p.fim
    GROUP BY m.airport_id
  ),
  strikes AS (
    SELECT s.airport_id,
           COUNT(*) FILTER (WHERE s.event_type = 'colisao_ave' AND COALESCE(s.inside_aerodrome, TRUE)) AS col_aves_site,
           COUNT(*) FILTER (WHERE s.event_type = 'colisao_ave' AND COALESCE(s.inside_aerodrome, FALSE) = FALSE) AS col_aves_asa,
           COUNT(*) FILTER (WHERE s.event_type = 'colisao_ave' AND s.damage_id IS NOT NULL AND COALESCE(s.inside_aerodrome, TRUE)) AS col_aves_site_dano,
           COUNT(*) FILTER (WHERE s.event_type = 'colisao_outro_animal') AS col_outros,
           COUNT(*) FILTER (WHERE s.event_type IN ('colisao_ave','colisao_outro_animal')) AS col_totais,
           COUNT(*) FILTER (WHERE COALESCE(s.quantity,1) > 1) AS col_multiplas,
           SUM(sp.mass_grams * COALESCE(s.quantity,1)) FILTER (WHERE sp.mass_grams IS NOT NULL)::numeric AS massa_total_grams
    FROM wildlife.fact_strike s
    LEFT JOIN wildlife.dim_species sp ON sp.species_id = s.species_id
    JOIN periodo p ON s.date_utc BETWEEN p.ini AND p.fim
    GROUP BY s.airport_id
  ),
  quase AS (
    SELECT s.airport_id, COUNT(*) AS quase_aves
    FROM wildlife.fact_strike s
    JOIN periodo p ON s.date_utc BETWEEN p.ini AND p.fim
    WHERE s.event_type = 'quase_colisao'
    GROUP BY s.airport_id
  ),
  avist AS (
    SELECT s.airport_id,
           COUNT(*) FILTER (WHERE tg.name = 'Aves') AS avist_aves,
           COUNT(*) FILTER (WHERE tg.name IS NULL OR tg.name <> 'Aves') AS avist_fauna
    FROM wildlife.fact_sighting s
    LEFT JOIN wildlife.fact_sighting_item si ON si.sighting_id = s.sighting_id
    LEFT JOIN wildlife.dim_species sp ON sp.species_id = si.species_id
    LEFT JOIN wildlife.lu_taxon_group tg ON tg.group_id = sp.group_id
    JOIN periodo p ON s.date_utc BETWEEN p.ini AND p.fim
    GROUP BY s.airport_id
  )
  SELECT
    a.airport_id,
    a.icao_code,
    a.name,
    mov.movimentos,
    CASE WHEN mov.movimentos > 0 THEN ROUND(COALESCE(str.col_aves_site,0)::numeric / mov.movimentos * 10000, 4) ELSE NULL END AS reavi_10k,
    CASE WHEN mov.movimentos > 0 THEN ROUND(COALESCE(str.col_aves_asa,0)::numeric / mov.movimentos * 10000, 4) ELSE NULL END AS reasa_10k,
    CASE WHEN COALESCE(str.col_aves_site,0) > 0 THEN ROUND(str.col_aves_site_dano::numeric / NULLIF(str.col_aves_site,0) * 100, 2) ELSE NULL END AS reavi_com_dano_pct,
    CASE WHEN mov.movimentos > 0 THEN ROUND(COALESCE(str.col_outros,0)::numeric / mov.movimentos * 10000, 4) ELSE NULL END AS refau_10k,
    CASE WHEN mov.movimentos > 0 THEN ROUND((COALESCE(avist.avist_aves,0) + COALESCE(quase.quase_aves,0))::numeric / mov.movimentos, 4) ELSE NULL END AS peavi_por_movimento,
    CASE WHEN mov.movimentos > 0 THEN ROUND(COALESCE(avist.avist_fauna,0)::numeric / mov.movimentos, 4) ELSE NULL END AS pefau_por_movimento,
    CASE WHEN mov.movimentos > 0 THEN ROUND(COALESCE(str.col_totais,0)::numeric / mov.movimentos * 10000, 4) ELSE NULL END AS sr10k,
    CASE WHEN COALESCE(str.col_totais,0) > 0 THEN ROUND(COALESCE(str.col_multiplas,0)::numeric / str.col_totais * 100, 2) ELSE NULL END AS pct_colisoes_multiplas,
    CASE WHEN COALESCE(str.col_totais,0) > 0 THEN ROUND(COALESCE(str.massa_total_grams,0)::numeric / str.col_totais / 1000, 3) ELSE NULL END AS massa_media_kg
  FROM wildlife.airport a
  LEFT JOIN mov ON mov.airport_id = a.airport_id
  LEFT JOIN strikes str ON str.airport_id = a.airport_id
  LEFT JOIN quase ON quase.airport_id = a.airport_id
  LEFT JOIN avist ON avist.airport_id = a.airport_id
  WHERE p_airport_id IS NULL OR a.airport_id = p_airport_id
  ORDER BY a.name;
$$ LANGUAGE SQL;

-------------------------------------------------------------------------------
-- Custos de colisões e controle de treinamento
-------------------------------------------------------------------------------

SET search_path = wildlife, public;

-------------------------------------------------------------------------------
ALTER TABLE IF EXISTS app_user
  ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS must_reset_password BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS password_changed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE TABLE IF NOT EXISTS fact_strike_cost (
  cost_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  strike_id    BIGINT NOT NULL REFERENCES fact_strike(strike_id) ON DELETE CASCADE,
  cost_type    TEXT NOT NULL CHECK (cost_type IN ('direto','indireto','outros')),
  amount_brl   NUMERIC(14,2) NOT NULL CHECK (amount_brl >= 0),
  description  TEXT,
  recorded_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_strike_cost_type ON fact_strike_cost (cost_type);

-------------------------------------------------------------------------------
-- Garantir dados básicos necessários para o seed de fact_strike em SBPS
-------------------------------------------------------------------------------
INSERT INTO airport (icao_code, iata_code, name, city, state, country, latitude_dec, longitude_dec, elevation_ft)
VALUES ('SBPS','BPS','Aeroporto de Porto Seguro','Porto Seguro','BA','Brasil', -16.438000, -39.081000, 168)
ON CONFLICT (icao_code) DO NOTHING;

WITH a AS (SELECT airport_id FROM airport WHERE icao_code='SBPS')
INSERT INTO dim_location (airport_id, code, runway_ref, description)
SELECT a.airport_id, v.code, v.runway_ref, v.description
FROM a, (VALUES
  ('PISTA','15/33','Cabeceiras e faixa de pista'),
  ('TAXIWAY',NULL,'Pistas de táxi'),
  ('PÁTIO',NULL,'Pátio e posições'),
  ('TERMINAL',NULL,'Terminal de passageiros'),
  ('ENTORNO',NULL,'ASA até 13 km')
) AS v(code, runway_ref, description)
ON CONFLICT DO NOTHING;

INSERT INTO lu_weather_precip (name) VALUES ('Sem'),('Fraca'),('Moderada'),('Forte')
ON CONFLICT DO NOTHING;

INSERT INTO lu_weather_wind (name) VALUES ('Calmo'),('Moderado'),('Forte')
ON CONFLICT DO NOTHING;

INSERT INTO lu_weather_visibility (name) VALUES ('Boa'),('Moderada'),('Restrita')
ON CONFLICT DO NOTHING;

INSERT INTO lu_phase_of_flight (name) VALUES
  ('Em solo'),('Decolagem'),('Subida inicial'),('Subida'),
  ('Cruzeiro'),('Aproximação'),('Pouso'),('Táxi')
ON CONFLICT DO NOTHING;

INSERT INTO lu_damage_class (name, severity_weight) VALUES
  ('Sem dano',1),('Leve',2),('Substancial',4),('Acidente',8)
ON CONFLICT DO NOTHING;

INSERT INTO lu_aircraft_engine_type (name) VALUES
  ('Turbofan'),('Turboélice'),('Pistão'),('Helicóptero'),('Desconhecido')
ON CONFLICT DO NOTHING;

INSERT INTO lu_mass_class (name) VALUES ('muito_peq'),('pequeno'),('medio'),('grande')
ON CONFLICT DO NOTHING;

INSERT INTO lu_effect_on_flight (name) VALUES
  ('Sem efeito'),('Desvio repentino'),('Desestabilização na aproximação'),
  ('Abandono de decolagem'),('Retorno ao aeroporto'),('Corte de motor'),
  ('Pane/alarme'),('Outro')
ON CONFLICT DO NOTHING;

INSERT INTO lu_part_hit (name) VALUES
  ('Nariz'),('Para-brisa'),('Asa'),('Fuselagem'),('Trem de pouso'),
  ('Motor'),('Hélice'),('Bordo de ataque'),('Empenagem'),('Outro')
ON CONFLICT DO NOTHING;

INSERT INTO lu_taxon_group (name) VALUES ('Aves'),('Morcegos'),('Mamíferos'),('Répteis'),('Anfíbios'),('Outros')
ON CONFLICT DO NOTHING;

WITH g AS (SELECT group_id, name FROM lu_taxon_group),
     m AS (SELECT mass_id, name FROM lu_mass_class)
INSERT INTO dim_species (common_name, scientific_name, group_id, mass_id, mass_grams, notes)
SELECT v.common, v.sci,
       (SELECT group_id FROM g WHERE name=v.grp),
       (SELECT mass_id FROM m WHERE name=v.mass),
       v.mass_grams,
       v.notes
FROM (VALUES
  ('Urubu-de-cabeça-preta','Coragyps atratus','Aves','medio', 1500.00,'Necrófago; alto risco em resíduos e carcaças'),
  ('Carcará','Caracara plancus','Aves','medio', 1200.00,'Aproveita carcaças; frequente em áreas abertas'),
  ('Quero-quero','Vanellus chilensis','Aves','pequeno', 300.00,'Territorial; comum em gramados baixos'),
  ('Garça-branca-grande','Ardea alba','Aves','medio', 1000.00,'Atrativa por lâminas d''água/drenagem'),
  ('Garça-vaqueira','Bubulcus ibis','Aves','pequeno', 350.00,'Associa-se a gramados e insetos'),
  ('Pomba-asa-branca','Patagioenas picazuro','Aves','pequeno', 250.00,'Granívora; bandos'),
  ('Andorinha-pequena-de-casa','Pygochelidon cyanoleuca','Aves','muito_peq', 18.00,'Ágil; atividade crepuscular/diurna'),
  ('Morcego-de-telha','Molossus molossus','Morcegos','muito_peq', 15.00,'Voo noturno; risco em iluminação'),
  ('Morcego-frugívoro','Artibeus lituratus','Morcegos','pequeno', 65.00,'Noturno; atração por frutíferas'),
  ('Tiziu','Volatinia jacarina','Aves','muito_peq', 11.00,'Gramados; insetívoro')
) AS v(common, sci, grp, mass, mass_grams, notes)
ON CONFLICT DO NOTHING;

-------------------------------------------------------------------------------
-- Seed fictitious strikes for SBPS (airport_id = 1) to support demos/tests
-------------------------------------------------------------------------------
DO $$
DECLARE
  v_airport_id BIGINT;
  v_start_date DATE := DATE '2023-01-01';
  v_end_date   DATE := DATE '2025-12-31';
  v_total_days INTEGER;
  v_inserted   INTEGER;
BEGIN
  SELECT airport_id
    INTO v_airport_id
  FROM wildlife.airport
  WHERE airport_id = 1;

  IF v_airport_id IS NULL THEN
    RAISE NOTICE 'Airport id 1 not found. Skipping wildlife.fact_strike seed.';
    RETURN;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM wildlife.dim_location WHERE airport_id = v_airport_id) THEN
    RAISE NOTICE 'No locations found for airport id %. Seed cancelled.', v_airport_id;
    RETURN;
  END IF;

  v_total_days := (v_end_date - v_start_date);

  DELETE FROM wildlife.fact_strike_cost c
  USING wildlife.fact_strike s
  WHERE c.strike_id = s.strike_id
    AND s.airport_id = v_airport_id
    AND s.date_utc BETWEEN v_start_date AND v_end_date;

  DELETE FROM wildlife.fact_strike_part p
  USING wildlife.fact_strike s
  WHERE p.strike_id = s.strike_id
    AND s.airport_id = v_airport_id
    AND s.date_utc BETWEEN v_start_date AND v_end_date;

  DELETE FROM wildlife.fact_strike
  WHERE airport_id = v_airport_id
    AND date_utc BETWEEN v_start_date AND v_end_date;

  WITH dados AS (
    SELECT
      gs AS seq,
      v_airport_id AS airport_id,
      (v_start_date + floor(random() * (v_total_days + 1))::int) AS date_utc,
      (TIME '00:00' + (interval '1 minute' * floor(random() * 1440)))::time AS time_local,
      (ARRAY['colisao_ave','colisao_outro_animal','quase_colisao'])[1 + floor(random() * 3)::int] AS event_type,
      (ARRAY['Alta','Media','Baixa','Nao_identificada'])[1 + floor(random() * 4)::int] AS id_confidence,
      (ARRAY[1,2,4,8])[1 + floor(random() * 4)::int] AS severity_weight,
      1 + floor(random() * 3)::int AS quantity,
      (SELECT location_id FROM wildlife.dim_location WHERE airport_id = v_airport_id ORDER BY random() LIMIT 1) AS location_id,
      (SELECT precip_id FROM wildlife.lu_weather_precip ORDER BY random() LIMIT 1) AS precip_id,
      (SELECT wind_id FROM wildlife.lu_weather_wind ORDER BY random() LIMIT 1) AS wind_id,
      (SELECT vis_id FROM wildlife.lu_weather_visibility ORDER BY random() LIMIT 1) AS vis_id,
      (SELECT phase_id FROM wildlife.lu_phase_of_flight ORDER BY random() LIMIT 1) AS phase_id,
      (SELECT species_id FROM wildlife.dim_species ORDER BY random() LIMIT 1) AS species_id,
      (SELECT damage_id FROM wildlife.lu_damage_class ORDER BY random() LIMIT 1) AS damage_id,
      (SELECT engine_type_id FROM wildlife.lu_aircraft_engine_type ORDER BY random() LIMIT 1) AS engine_type_id,
      (SELECT mass_id FROM wildlife.lu_mass_class ORDER BY random() LIMIT 1) AS est_mass_id,
      (SELECT effect_id FROM wildlife.lu_effect_on_flight ORDER BY random() LIMIT 1) AS effect_id,
      (SELECT part_id FROM wildlife.lu_part_hit ORDER BY random() LIMIT 1) AS part_id,
      (SELECT part_id FROM wildlife.lu_part_hit ORDER BY random() LIMIT 1) AS part_aux_id,
      round((random() * 50000)::numeric, 2) AS custo_direto,
      round((random() * 15000)::numeric, 2) AS custo_indireto,
      round((random() * 5000)::numeric, 2) AS custo_outros
    FROM generate_series(1, 50) gs
  ),
  dados_ord AS (
    SELECT ROW_NUMBER() OVER (ORDER BY seq) AS rn, d.*
    FROM dados d
  ),
  inseridos AS (
    INSERT INTO wildlife.fact_strike (
      airport_id,
      date_utc,
      time_local,
      location_id,
      precip_id,
      wind_id,
      vis_id,
      phase_id,
      species_id,
      event_type,
      id_confidence,
      quantity,
      damage_id,
      effect_id,
      part_id,
      time_out_hours,
      cost_brl,
      sample_collected,
      severity_weight,
      aircraft_registration,
      aircraft_type,
      engine_type_id,
      near_miss,
      pilot_alerted,
      flight_delay,
      delay_minutes,
      est_mass_id,
      reporter_name,
      reporter_contact,
      notes
    )
    SELECT
      d.airport_id,
      d.date_utc,
      d.time_local,
      d.location_id,
      d.precip_id,
      d.wind_id,
      d.vis_id,
      d.phase_id,
      d.species_id,
      d.event_type,
      d.id_confidence,
      d.quantity,
      d.damage_id,
      d.effect_id,
      d.part_id,
      round((random() * 6)::numeric, 2),
      round((d.custo_direto + d.custo_indireto + d.custo_outros)::numeric, 2),
      (random() < 0.3),
      d.severity_weight,
      CONCAT('PR-', upper(substr(md5(random()::text), 1, 3))),
      CONCAT('Aeronave teste ', d.seq),
      d.engine_type_id,
      (random() < 0.25),
      (random() < 0.5),
      (random() < 0.2),
      CASE WHEN random() < 0.2 THEN round((random() * 60)::numeric, 2) END,
      d.est_mass_id,
      CONCAT('Operador ', d.seq),
      CONCAT('+55 73 9', lpad((floor(random() * 99999999))::text, 8, '0')),
      'Registro gerado automaticamente para testes'
    FROM dados_ord d
    ORDER BY d.rn
    RETURNING strike_id, ROW_NUMBER() OVER (ORDER BY ctid) AS rn
  ),
  custos AS (
    INSERT INTO wildlife.fact_strike_cost (strike_id, cost_type, amount_brl, description)
    SELECT i.strike_id, 'direto', round(d.custo_direto, 2), 'Custo direto simulado'
    FROM inseridos i
    JOIN dados_ord d ON d.rn = i.rn
    WHERE d.custo_direto > 0
    UNION ALL
    SELECT i.strike_id, 'indireto', round(d.custo_indireto, 2), 'Custo indireto simulado'
    FROM inseridos i
    JOIN dados_ord d ON d.rn = i.rn
    WHERE d.custo_indireto > 0
    UNION ALL
    SELECT i.strike_id, 'outros', round(d.custo_outros, 2), 'Custos diversos simulados'
    FROM inseridos i
    JOIN dados_ord d ON d.rn = i.rn
    WHERE d.custo_outros > 0
  ),
  partes AS (
    INSERT INTO wildlife.fact_strike_part (strike_id, part_id)
    SELECT i.strike_id, d.part_id
    FROM inseridos i
    JOIN dados_ord d ON d.rn = i.rn
    WHERE d.part_id IS NOT NULL
    UNION ALL
    SELECT i.strike_id, d.part_aux_id
    FROM inseridos i
    JOIN dados_ord d ON d.rn = i.rn
    WHERE d.part_aux_id IS NOT NULL
      AND d.part_aux_id <> d.part_id
  )
  SELECT COUNT(*) INTO v_inserted FROM inseridos;

  RAISE NOTICE 'Seeded % wildlife.fact_strike rows for airport %', COALESCE(v_inserted, 0), v_airport_id;
END $$;

CREATE TABLE IF NOT EXISTS dim_personnel (
  personnel_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  airport_id   BIGINT REFERENCES airport(airport_id) ON DELETE SET NULL,
  name         TEXT NOT NULL,
  last_name    TEXT,
  role         TEXT NOT NULL,
  organization TEXT,
  email        TEXT,
  phone        TEXT,
  cpf          TEXT,
  notes        TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_dim_personnel_upd') THEN
    CREATE TRIGGER trg_dim_personnel_upd
      BEFORE UPDATE ON dim_personnel
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

ALTER TABLE IF EXISTS dim_personnel
  ADD COLUMN IF NOT EXISTS last_name TEXT,
  ADD COLUMN IF NOT EXISTS cpf TEXT,
  ADD COLUMN IF NOT EXISTS email TEXT,
  ADD COLUMN IF NOT EXISTS phone TEXT;

CREATE TABLE IF NOT EXISTS fact_training_completion (
  completion_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  training_id      BIGINT REFERENCES fact_training_session(training_id) ON DELETE SET NULL,
  personnel_id     BIGINT NOT NULL REFERENCES dim_personnel(personnel_id) ON DELETE CASCADE,
  completion_date  DATE NOT NULL,
  hours            NUMERIC(6,2) CHECK (hours IS NULL OR hours >= 0),
  validity_months  INTEGER CHECK (validity_months IS NULL OR validity_months >= 0),
  valid_until      DATE,
  status           TEXT NOT NULL DEFAULT 'valido' CHECK (status IN ('valido','expirado','pendente')),
  certificate_url  TEXT,
  notes            TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_training_completion_status
  ON fact_training_completion (status);

CREATE OR REPLACE FUNCTION refresh_training_completion_status()
RETURNS TRIGGER AS $$
DECLARE
  venc DATE;
BEGIN
  IF NEW.validity_months IS NOT NULL THEN
    venc := (NEW.completion_date + (NEW.validity_months || ' months')::interval)::date;
  ELSE
    venc := NULL;
  END IF;
  NEW.valid_until := venc;
  IF NEW.status IS NULL OR NEW.status NOT IN ('valido','expirado','pendente') THEN
    NEW.status := 'valido';
  END IF;
  IF NEW.status = 'pendente' THEN
    RETURN NEW;
  END IF;
  IF venc IS NOT NULL THEN
    IF venc < CURRENT_DATE THEN
      NEW.status := 'expirado';
    ELSE
      NEW.status := 'valido';
    END IF;
  END IF;
  RETURN NEW;
END; $$ LANGUAGE plpgsql;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_training_completion_upd') THEN
    CREATE TRIGGER trg_training_completion_upd
      BEFORE INSERT OR UPDATE ON fact_training_completion
      FOR EACH ROW EXECUTE FUNCTION refresh_training_completion_status();
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_training_completion_ts') THEN
    CREATE TRIGGER trg_training_completion_ts
      BEFORE UPDATE ON fact_training_completion
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

COMMIT;






