
-- ======================================================================
-- WILDLIFE SAFETY DB - FULL PACKAGE
-- (DDL + seed + KPIs + stats + DiD + PostGIS BA)
-- ======================================================================

CREATE EXTENSION IF NOT EXISTS postgis;

CREATE SCHEMA IF NOT EXISTS wildlife;
SET search_path TO wildlife, public;

-- Airport
CREATE TABLE IF NOT EXISTS airport (
  airport_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  icao_code         VARCHAR(4)  NOT NULL UNIQUE,
  iata_code         VARCHAR(3),
  name              TEXT        NOT NULL,
  city              TEXT,
  state             TEXT,
  country           TEXT DEFAULT 'Brasil',
  latitude_dec      NUMERIC(9,6),
  longitude_dec     NUMERIC(9,6),
  elevation_ft      INTEGER,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT airport_latlon_chk CHECK (
    latitude_dec BETWEEN -90 AND 90 AND longitude_dec BETWEEN -180 AND 180
  )
);

-- Lookups
CREATE TABLE IF NOT EXISTS lu_phase_of_flight (phase_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS lu_damage_class (damage_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT UNIQUE NOT NULL, severity_weight SMALLINT NOT NULL CHECK (severity_weight IN (1,2,4,8)));
CREATE TABLE IF NOT EXISTS lu_detection_method (method_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS lu_weather_visibility (vis_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS lu_weather_wind (wind_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS lu_weather_precip (precip_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS lu_effect_on_flight (effect_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS lu_part_hit (part_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS lu_taxon_group (group_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS lu_mass_class (mass_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS lu_attractor_type (attractor_type_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS lu_action_type (action_type_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS lu_aircraft_engine_type (engine_type_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT UNIQUE NOT NULL);

-- Dimensions
CREATE TABLE IF NOT EXISTS dim_location (
  location_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  airport_id  BIGINT NOT NULL REFERENCES airport(airport_id) ON DELETE CASCADE,
  code        TEXT NOT NULL,
  runway_ref  TEXT,
  description TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_dim_location_airport_code_runway
  ON dim_location (airport_id, code, COALESCE(runway_ref,''));

CREATE TABLE IF NOT EXISTS dim_species (
  species_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  common_name     TEXT NOT NULL,
  scientific_name TEXT,
  group_id        SMALLINT NOT NULL REFERENCES lu_taxon_group(group_id),
  mass_id         SMALLINT REFERENCES lu_mass_class(mass_id),
  mass_grams      NUMERIC(10,2) CHECK (mass_grams IS NULL OR mass_grams > 0),
  notes           TEXT,
  UNIQUE (LOWER(common_name), COALESCE(LOWER(scientific_name), ''))
);
CREATE INDEX IF NOT EXISTS idx_species_common ON dim_species (LOWER(common_name));
CREATE INDEX IF NOT EXISTS idx_species_scient ON dim_species (LOWER(scientific_name));

-- Facts
CREATE TABLE IF NOT EXISTS fact_movement (
  movement_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  airport_id        BIGINT NOT NULL REFERENCES airport(airport_id) ON DELETE CASCADE,
  date_utc          DATE NOT NULL,
  time_local        TIME,
  movement_type     TEXT CHECK (movement_type IN ('Pouso','Decolagem')),
  runway            TEXT,
  aircraft_type     TEXT,
  engine_type_id    SMALLINT REFERENCES lu_aircraft_engine_type(engine_type_id),
  movements_in_day  INTEGER CHECK (movements_in_day >= 0),
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_mv_air_date ON fact_movement (airport_id, date_utc);
CREATE INDEX IF NOT EXISTS idx_mv_runway   ON fact_movement (runway);

CREATE TABLE IF NOT EXISTS fact_sighting (
  sighting_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  airport_id        BIGINT NOT NULL REFERENCES airport(airport_id) ON DELETE CASCADE,
  date_utc          DATE NOT NULL,
  time_local        TIME NOT NULL,
  location_id       BIGINT NOT NULL REFERENCES dim_location(location_id) ON DELETE RESTRICT,
  latitude_dec      NUMERIC(9,6),
  longitude_dec     NUMERIC(9,6),
  detection_method  SMALLINT REFERENCES lu_detection_method(method_id),
  effort_hours      NUMERIC(6,2) CHECK (effort_hours >= 0),
  effort_km         NUMERIC(7,2) CHECK (effort_km >= 0),
  effort_area_ha    NUMERIC(9,2) CHECK (effort_area_ha >= 0),
  precip_id         SMALLINT REFERENCES lu_weather_precip(precip_id),
  wind_id           SMALLINT REFERENCES lu_weather_wind(wind_id),
  vis_id            SMALLINT REFERENCES lu_weather_visibility(vis_id),
  photo_url         TEXT,
  confidence_overall TEXT,
  observer_team     TEXT,
  notes             TEXT,
  geom              geometry(Point, 4326),
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT sight_latlon_chk CHECK (latitude_dec BETWEEN -90 AND 90 AND longitude_dec BETWEEN -180 AND 180)
);
CREATE INDEX IF NOT EXISTS idx_sighting_air_date ON fact_sighting (airport_id, date_utc);
CREATE INDEX IF NOT EXISTS idx_sighting_loc      ON fact_sighting (location_id);
CREATE INDEX IF NOT EXISTS idx_sighting_geom     ON fact_sighting USING GIST (geom);

CREATE TABLE IF NOT EXISTS fact_sighting_item (
  sighting_item_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sighting_id       BIGINT NOT NULL REFERENCES fact_sighting(sighting_id) ON DELETE CASCADE,
  species_id        BIGINT REFERENCES dim_species(species_id),
  quantity          INTEGER CHECK (quantity >= 1),
  behavior          TEXT,
  id_confidence     TEXT CHECK (id_confidence IN ('Alta','Media','Baixa')),
  UNIQUE (sighting_id, species_id, behavior)
);
CREATE INDEX IF NOT EXISTS idx_sighting_item_species ON fact_sighting_item (species_id);

CREATE TABLE IF NOT EXISTS fact_strike (
  strike_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  airport_id        BIGINT NOT NULL REFERENCES airport(airport_id) ON DELETE CASCADE,
  date_utc          DATE NOT NULL,
  time_local        TIME NOT NULL,
  location_id       BIGINT NOT NULL REFERENCES dim_location(location_id) ON DELETE RESTRICT,
  latitude_dec      NUMERIC(9,6),
  longitude_dec     NUMERIC(9,6),
  phase_id          SMALLINT REFERENCES lu_phase_of_flight(phase_id),
  species_id        BIGINT REFERENCES dim_species(species_id),
  id_confidence     TEXT CHECK (id_confidence IN ('Alta','Media','Baixa','Nao_identificada')),
  quantity          INTEGER CHECK (quantity IS NULL OR quantity >= 1),
  damage_id         SMALLINT REFERENCES lu_damage_class(damage_id),
  ingestion         BOOLEAN,
  effect_id         SMALLINT REFERENCES lu_effect_on_flight(effect_id),
  part_id           SMALLINT REFERENCES lu_part_hit(part_id),
  time_out_hours    NUMERIC(8,2) CHECK (time_out_hours IS NULL OR time_out_hours >= 0),
  cost_brl          NUMERIC(14,2) CHECK (cost_brl IS NULL OR cost_brl >= 0),
  sample_collected  BOOLEAN,
  severity_weight   SMALLINT CHECK (severity_weight IN (1,2,4,8)),
  source_ref        TEXT,
  notes             TEXT,
  geom              geometry(Point, 4326),
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT strike_latlon_chk CHECK (latitude_dec BETWEEN -90 AND 90 AND longitude_dec BETWEEN -180 AND 180)
);
CREATE INDEX IF NOT EXISTS idx_strike_air_date ON fact_strike (airport_id, date_utc);
CREATE INDEX IF NOT EXISTS idx_strike_species  ON fact_strike (species_id);
CREATE INDEX IF NOT EXISTS idx_strike_loc      ON fact_strike (location_id);
CREATE INDEX IF NOT EXISTS idx_strike_geom     ON fact_strike USING GIST (geom);

CREATE TABLE IF NOT EXISTS fact_control_action (
  action_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  airport_id        BIGINT NOT NULL REFERENCES airport(airport_id) ON DELETE CASCADE,
  date_utc          DATE NOT NULL,
  time_local        TIME,
  location_id       BIGINT REFERENCES dim_location(location_id) ON DELETE SET NULL,
  latitude_dec      NUMERIC(9,6),
  longitude_dec     NUMERIC(9,6),
  action_type_id    SMALLINT REFERENCES lu_action_type(action_type_id),
  description       TEXT,
  duration_min      INTEGER CHECK (duration_min IS NULL OR duration_min >= 0),
  result_notes      TEXT,
  efficacy_percent  NUMERIC(5,2) CHECK (efficacy_percent BETWEEN -100 AND 100),
  lethal_control    BOOLEAN DEFAULT FALSE,
  weapon_ammo       TEXT,
  post_dispersion_m DECIMAL(10,2),
  geom              geometry(Point, 4326),
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT action_latlon_chk CHECK (latitude_dec BETWEEN -90 AND 90 AND longitude_dec BETWEEN -180 AND 180)
);
CREATE INDEX IF NOT EXISTS idx_action_air_date ON fact_control_action (airport_id, date_utc);
CREATE INDEX IF NOT EXISTS idx_action_geom     ON fact_control_action USING GIST (geom);

CREATE TABLE IF NOT EXISTS fact_attractor (
  attractor_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  airport_id        BIGINT NOT NULL REFERENCES airport(airport_id) ON DELETE CASCADE,
  date_utc          DATE NOT NULL,
  latitude_dec      NUMERIC(9,6),
  longitude_dec     NUMERIC(9,6),
  attractor_type_id SMALLINT REFERENCES lu_attractor_type(attractor_type_id),
  description       TEXT,
  distance_m_runway NUMERIC(10,2) CHECK (distance_m_runway IS NULL OR distance_m_runway >= 0),
  status            TEXT CHECK (status IN ('ativo','mitigando','resolvido')),
  responsible_org   TEXT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT attractor_latlon_chk CHECK (latitude_dec BETWEEN -90 AND 90 AND longitude_dec BETWEEN -180 AND 180)
);
CREATE INDEX IF NOT EXISTS idx_attractor_air_date ON fact_attractor (airport_id, date_utc);

-- Trigger for updated_at
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END; $$ LANGUAGE plpgsql;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_airport_upd') THEN
    CREATE TRIGGER trg_airport_upd          BEFORE UPDATE ON airport             FOR EACH ROW EXECUTE FUNCTION set_updated_at();
    CREATE TRIGGER trg_movement_upd         BEFORE UPDATE ON fact_movement       FOR EACH ROW EXECUTE FUNCTION set_updated_at();
    CREATE TRIGGER trg_sighting_upd         BEFORE UPDATE ON fact_sighting       FOR EACH ROW EXECUTE FUNCTION set_updated_at();
    CREATE TRIGGER trg_strike_upd           BEFORE UPDATE ON fact_strike         FOR EACH ROW EXECUTE FUNCTION set_updated_at();
    CREATE TRIGGER trg_action_upd           BEFORE UPDATE ON fact_control_action FOR EACH ROW EXECUTE FUNCTION set_updated_at();
    CREATE TRIGGER trg_attractor_upd        BEFORE UPDATE ON fact_attractor      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
    CREATE TRIGGER trg_location_upd         BEFORE UPDATE ON dim_location        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

-- Seeds
INSERT INTO lu_phase_of_flight (name) VALUES
  ('Em solo'),('Decolagem'),('Subida inicial'),('Subida'),
  ('Cruzeiro'),('Aproximação'),('Pouso'),('Táxi')
ON CONFLICT DO NOTHING;

INSERT INTO lu_damage_class (name, severity_weight) VALUES
  ('Sem dano',1),('Leve',2),('Substancial',4),('Acidente',8)
ON CONFLICT DO NOTHING;

INSERT INTO lu_detection_method (name) VALUES
  ('Patrulha'),('Tripulação'),('Torre'),('Radar/Óptico'),('Terceiros')
ON CONFLICT DO NOTHING;

INSERT INTO lu_weather_visibility (name) VALUES ('Boa'),('Moderada'),('Restrita')
ON CONFLICT DO NOTHING;

INSERT INTO lu_weather_wind (name) VALUES ('Calmo'),('Moderado'),('Forte')
ON CONFLICT DO NOTHING;

INSERT INTO lu_weather_precip (name) VALUES ('Sem'),('Fraca'),('Moderada'),('Forte')
ON CONFLICT DO NOTHING;

INSERT INTO lu_effect_on_flight (name) VALUES
  ('Sem efeito'),('Desvio repentino'),('Desestabilização na aproximação'),
  ('Abandono de decolagem'),('Retorno ao aeroporto'),('Corte de motor'),
  ('Pane/alarme'),('Outro')
ON CONFLICT DO NOTHING;

INSERT INTO lu_part_hit (name) VALUES
  ('Nariz'),('Para-brisa'),('Asa'),('Fuselagem'),('Trem de pouso'),
  ('Motor'),('Hélice'),('Bordo de ataque'),('Empenagem'),('Outro')
ON CONFLICT DO NOTHING;

INSERT INTO lu_taxon_group (name) VALUES ('Aves'),('Morcegos'),('Mamíferos'),('Répteis'),('Anfíbios'),('Outros')
ON CONFLICT DO NOTHING;

INSERT INTO lu_mass_class (name) VALUES ('muito_peq'),('pequeno'),('medio'),('grande')
ON CONFLICT DO NOTHING;

INSERT INTO lu_attractor_type (name) VALUES ('Água'),('Resíduos'),('Gramado'),('Drenagem'),('Agricultura'),('Abrigo'),('Outros')
ON CONFLICT DO NOTHING;

INSERT INTO lu_action_type (name) VALUES
  ('Afugentamento'),('Manejo de gramado'),('Drenagem'),
  ('Gestão de resíduos'),('Exclusão física'),('Treinamento'),('Outros')
ON CONFLICT DO NOTHING;

INSERT INTO lu_aircraft_engine_type (name) VALUES
  ('Turbofan'),('Turboélice'),('Pistão'),('Helicóptero'),('Desconhecido')
ON CONFLICT DO NOTHING;

-- SBPS + locations
INSERT INTO airport (icao_code, iata_code, name, city, state, country, latitude_dec, longitude_dec, elevation_ft)
VALUES ('SBPS','BPS','Aeroporto de Porto Seguro','Porto Seguro','BA','Brasil', -16.438000, -39.081000, 168)
ON CONFLICT (icao_code) DO NOTHING;

WITH a AS (SELECT airport_id FROM airport WHERE icao_code='SBPS')
INSERT INTO dim_location (airport_id, code, runway_ref, description)
SELECT a.airport_id, v.code, v.runway_ref, v.description
FROM a, (VALUES
  ('PISTA','15/33','Cabeceiras e faixa de pista'),
  ('TAXIWAY',NULL,'Pistas de táxi'),
  ('PÁTIO',NULL,'Pátio e posições'),
  ('TERMINAL',NULL,'Terminal de passageiros'),
  ('ENTORNO',NULL,'ASA até 13 km')
) AS v(code, runway_ref, description)
ON CONFLICT DO NOTHING;

-- Species (with mass_grams)
WITH g AS (SELECT group_id, name FROM lu_taxon_group),
     m AS (SELECT mass_id, name FROM lu_mass_class)
INSERT INTO dim_species (common_name, scientific_name, group_id, mass_id, mass_grams, notes)
SELECT v.common, v.sci,
       (SELECT group_id FROM g WHERE name=v.grp),
       (SELECT mass_id FROM m WHERE name=v.mass),
       v.mass_grams,
       v.notes
FROM (VALUES
  ('Urubu-de-cabeça-preta','Coragyps atratus','Aves','medio', 1500.00,'Necrófago; alto risco em resíduos e carcaças'),
  ('Carcará','Caracara plancus','Aves','medio', 1200.00,'Aproveita carcaças; frequente em áreas abertas'),
  ('Quero-quero','Vanellus chilensis','Aves','pequeno', 300.00,'Territorial; comum em gramados baixos'),
  ('Garça-branca-grande','Ardea alba','Aves','medio', 1000.00,'Atrativa por lâminas d’água/drenagem'),
  ('Garça-vaqueira','Bubulcus ibis','Aves','pequeno', 350.00,'Associa-se a gramados e insetos'),
  ('Pomba-asa-branca','Patagioenas picazuro','Aves','pequeno', 250.00,'Granívora; bandos'),
  ('Andorinha-pequena-de-casa','Pygochelidon cyanoleuca','Aves','muito_peq', 18.00,'Aérea; atividade crepuscular/diurna'),
  ('Morcego-de-telha','Molossus molossus','Morcegos','muito_peq', 15.00,'Voo noturno; risco em iluminação'),
  ('Morcego-frugívoro','Artibeus lituratus','Morcegos','pequeno', 65.00,'Noturno; atração por frutíferas'),
  ('Tiziu','Volatinia jacarina','Aves','muito_peq', 11.00,'Gramados; insetívoro')
) AS v(common, sci, grp, mass, mass_grams, notes)
ON CONFLICT DO NOTHING;

-- KPI schema
CREATE SCHEMA IF NOT EXISTS wildlife_kpi;
SET search_path TO wildlife_kpi, wildlife, public;

CREATE OR REPLACE VIEW params_default_period AS
SELECT date_trunc('year', CURRENT_DATE)::date AS dt_ini,
       (date_trunc('year', CURRENT_DATE) + INTERVAL '1 year - 1 day')::date AS dt_fim;

CREATE OR REPLACE VIEW v_movements_daily AS
SELECT m.airport_id, m.date_utc AS day, COALESCE(SUM(m.movements_in_day), COUNT(*))::bigint AS movements
FROM wildlife.fact_movement m
GROUP BY m.airport_id, m.date_utc;

CREATE OR REPLACE VIEW v_strikes_daily AS
SELECT s.airport_id, s.date_utc AS day,
       COUNT(*)::bigint AS strikes,
       COUNT(*) FILTER (WHERE d.name IS DISTINCT FROM 'Sem dano')::bigint AS strikes_com_dano,
       AVG(s.severity_weight)::numeric(10,4) AS severidade_media_peso
FROM wildlife.fact_strike s
LEFT JOIN wildlife.lu_damage_class d ON d.damage_id = s.damage_id
GROUP BY s.airport_id, s.date_utc;

CREATE OR REPLACE VIEW v_sightings_effort_daily AS
SELECT si.airport_id, s.date_utc AS day,
       COUNT(si.sighting_item_id)::bigint AS avistamentos_itens,
       COALESCE(SUM(s.effort_hours),0)::numeric(10,2)  AS horas_patrulha,
       COALESCE(SUM(s.effort_km),0)::numeric(10,2)     AS km_patrulha,
       COALESCE(SUM(s.effort_area_ha),0)::numeric(10,2)AS area_amostrada_ha
FROM wildlife.fact_sighting_item si
JOIN wildlife.fact_sighting s ON s.sighting_id = si.sighting_id
GROUP BY si.airport_id, s.date_utc;

CREATE OR REPLACE VIEW v_movements_monthly AS
SELECT airport_id, date_trunc('month', day)::date AS mes, SUM(movements)::bigint AS movements
FROM v_movements_daily
GROUP BY airport_id, date_trunc('month', day);

CREATE OR REPLACE VIEW v_strikes_monthly AS
SELECT airport_id, date_trunc('month', day)::date AS mes,
       SUM(strikes)::bigint AS strikes,
       SUM(strikes_com_dano)::bigint AS strikes_com_dano,
       AVG(severidade_media_peso)::numeric(10,4) AS severidade_media_peso
FROM v_strikes_daily
GROUP BY airport_id, date_trunc('month', day);

CREATE OR REPLACE VIEW v_sightings_effort_monthly AS
SELECT airport_id, date_trunc('month', day)::date AS mes,
       SUM(avistamentos_itens)::bigint AS avistamentos_itens,
       SUM(horas_patrulha)::numeric(12,2) AS horas_patrulha,
       SUM(km_patrulha)::numeric(12,2) AS km_patrulha,
       SUM(area_amostrada_ha)::numeric(12,2) AS area_amostrada_ha
FROM v_sightings_effort_daily
GROUP BY airport_id, date_trunc('month', day);

-- KPIs
CREATE OR REPLACE VIEW kpi_sr_10k AS
WITH p AS (SELECT * FROM params_default_period)
SELECT m.airport_id,
       SUM(s.strikes) AS strikes,
       SUM(m.movements) AS movimentos,
       CASE WHEN SUM(m.movements) > 0 THEN ROUND((SUM(s.strikes)::numeric / SUM(m.movements)::numeric) * 10000, 4) ELSE NULL END AS sr_10k,
       (SELECT icao_code FROM wildlife.airport a WHERE a.airport_id=m.airport_id) AS icao
FROM v_movements_daily m
LEFT JOIN v_strikes_daily s ON s.airport_id=m.airport_id AND s.day=m.day
CROSS JOIN p
WHERE m.day BETWEEN p.dt_ini AND p.dt_fim
GROUP BY m.airport_id;

CREATE OR REPLACE VIEW kpi_damage_rate_10k AS
WITH p AS (SELECT * FROM params_default_period)
SELECT m.airport_id,
       SUM(s.strikes_com_dano) AS strikes_com_dano,
       SUM(m.movements) AS movimentos,
       CASE WHEN SUM(m.movements) > 0 THEN ROUND((SUM(s.strikes_com_dano)::numeric / SUM(m.movements)::numeric) * 10000, 4) ELSE NULL END AS damage_rate_10k,
       (SELECT icao_code FROM wildlife.airport a WHERE a.airport_id=m.airport_id) AS icao
FROM v_movements_daily m
LEFT JOIN v_strikes_daily s ON s.airport_id=m.airport_id AND s.day=m.day
CROSS JOIN p
WHERE m.day BETWEEN p.dt_ini AND p.dt_fim
GROUP BY m.airport_id;

CREATE OR REPLACE VIEW kpi_pct_damage AS
WITH p AS (SELECT * FROM params_default_period)
SELECT s.airport_id,
       SUM(s.strikes_com_dano) AS strikes_com_dano,
       SUM(s.strikes) AS strikes_total,
       CASE WHEN SUM(s.strikes)>0 THEN ROUND((SUM(s.strikes_com_dano)::numeric / SUM(s.strikes)::numeric) * 100, 2) ELSE NULL END AS pct_com_dano,
       (SELECT icao_code FROM wildlife.airport a WHERE a.airport_id=s.airport_id) AS icao
FROM v_strikes_daily s, p
WHERE s.day BETWEEN p.dt_ini AND p.dt_fim
GROUP BY s.airport_id;

CREATE OR REPLACE VIEW kpi_tah AS
WITH p AS (SELECT * FROM params_default_period)
SELECT e.airport_id,
       SUM(e.avistamentos_itens) AS avist_itens,
       SUM(e.horas_patrulha) AS horas_patrulha,
       CASE WHEN SUM(e.horas_patrulha)>0 THEN ROUND(SUM(e.avistamentos_itens)::numeric / SUM(e.horas_patrulha), 4) ELSE NULL END AS tah_itens_por_hora,
       (SELECT icao_code FROM wildlife.airport a WHERE a.airport_id=e.airport_id) AS icao
FROM v_sightings_effort_daily e, p
WHERE e.day BETWEEN p.dt_ini AND p.dt_fim
GROUP BY e.airport_id;

CREATE OR REPLACE VIEW kpi_severity_weight_avg AS
WITH p AS (SELECT * FROM params_default_period)
SELECT s.airport_id,
       AVG(s.severidade_media_peso)::numeric(10,4) AS severidade_media_peso_diaria,
       (SELECT icao_code FROM wildlife.airport a WHERE a.airport_id=s.airport_id) AS icao
FROM v_strikes_daily s, p
WHERE s.day BETWEEN p.dt_ini AND p.dt_fim
GROUP BY s.airport_id;

CREATE OR REPLACE VIEW kpi_pct_species_identified AS
WITH p AS (SELECT * FROM params_default_period)
SELECT s.airport_id,
       COUNT(*) AS strikes_total,
       COUNT(*) FILTER (WHERE s.species_id IS NOT NULL) AS strikes_identificados,
       CASE WHEN COUNT(*)>0 THEN ROUND((COUNT(*) FILTER (WHERE s.species_id IS NOT NULL))::numeric / COUNT(*)::numeric * 100, 2) ELSE NULL END AS pct_identificados,
       (SELECT icao_code FROM wildlife.airport a WHERE a.airport_id=s.airport_id) AS icao
FROM wildlife.fact_strike s, p
WHERE s.date_utc BETWEEN p.dt_ini AND p.dt_fim
GROUP BY s.airport_id;

CREATE OR REPLACE VIEW rpt_pareto_species_strike AS
WITH p AS (SELECT * FROM params_default_period)
SELECT s.airport_id,
       COALESCE(ds.common_name, 'Não identificada') AS especie,
       COUNT(*)::bigint AS strikes
FROM wildlife.fact_strike s
LEFT JOIN wildlife.dim_species ds ON ds.species_id = s.species_id, p
WHERE s.date_utc BETWEEN p.dt_ini AND p.dt_fim
GROUP BY s.airport_id, especie
ORDER BY s.airport_id, strikes DESC;

CREATE OR REPLACE VIEW rpt_strikes_by_phase AS
WITH p AS (SELECT * FROM params_default_period)
SELECT s.airport_id, pf.name AS fase_voo, COUNT(*)::bigint AS strikes
FROM wildlife.fact_strike s
LEFT JOIN wildlife.lu_phase_of_flight pf ON pf.phase_id = s.phase_id, p
WHERE s.date_utc BETWEEN p.dt_ini AND p.dt_fim
GROUP BY s.airport_id, pf.name
ORDER BY s.airport_id, strikes DESC;

CREATE OR REPLACE VIEW rpt_damage_by_part AS
WITH p AS (SELECT * FROM params_default_period)
SELECT s.airport_id, ph.name AS parte_atingida,
       COUNT(*) FILTER (WHERE d.name IS DISTINCT FROM 'Sem dano')::bigint AS eventos_com_dano,
       COUNT(*)::bigint AS eventos_total,
       CASE WHEN COUNT(*)>0 THEN ROUND((COUNT(*) FILTER (WHERE d.name IS DISTINCT FROM 'Sem dano'))::numeric / COUNT(*)::numeric * 100, 2) ELSE NULL END AS pct_com_dano
FROM wildlife.fact_strike s
LEFT JOIN wildlife.lu_part_hit ph ON ph.part_id = s.part_id
LEFT JOIN wildlife.lu_damage_class d ON d.damage_id = s.damage_id, p
WHERE s.date_utc BETWEEN p.dt_ini AND p.dt_fim
GROUP BY s.airport_id, ph.name
ORDER BY s.airport_id, pct_com_dano DESC NULLS LAST;

-- MM real
CREATE OR REPLACE VIEW kpi_mm_real AS
WITH p AS (SELECT * FROM params_default_period)
SELECT s.airport_id,
       SUM( (sp.mass_grams * COALESCE(s.quantity,1)) )::numeric(18,2) AS massa_total_grams,
       (SELECT icao_code FROM wildlife.airport a WHERE a.airport_id=s.airport_id) AS icao
FROM wildlife.fact_strike s
JOIN wildlife.dim_species sp ON sp.species_id = s.species_id, p
WHERE s.date_utc BETWEEN p.dt_ini AND p.dt_fim
GROUP BY s.airport_id;

CREATE OR REPLACE VIEW kpi_mm_real_por_1M AS
WITH p AS (SELECT * FROM params_default_period),
mov AS (
  SELECT airport_id, SUM(COALESCE(movements_in_day,1))::numeric AS movimentos
  FROM wildlife.fact_movement, p
  WHERE date_utc BETWEEN p.dt_ini AND p.dt_fim
  GROUP BY airport_id
)
SELECT m.airport_id, k.massa_total_grams, m.movimentos,
       CASE WHEN m.movimentos>0 THEN ROUND((k.massa_total_grams / m.movimentos) * 1000000, 6) ELSE NULL END AS mm_real_por_1M,
       (SELECT icao_code FROM wildlife.airport a WHERE a.airport_id=m.airport_id) AS icao
FROM mov m LEFT JOIN kpi_mm_real k ON k.airport_id=m.airport_id;

-- Stats functions
CREATE OR REPLACE FUNCTION kpi_sr10k_byar(k_count NUMERIC, exposure NUMERIC)
RETURNS TABLE (sr10k NUMERIC, lcl10k NUMERIC, ucl10k NUMERIC)
LANGUAGE sql AS $$
SELECT
  CASE WHEN exposure>0 THEN ROUND((k_count/exposure)*10000, 6) ELSE NULL END,
  CASE WHEN k_count IS NULL OR exposure<=0 THEN NULL
       WHEN k_count=0 THEN 0
       ELSE ROUND( ( (k_count * POWER(1 - 1.0/(9*k_count) - 1.96/(3*SQRT(k_count)), 3)) / exposure )*10000 , 6) END,
  CASE WHEN k_count IS NULL OR exposure<=0 THEN NULL
       WHEN k_count=0 THEN ROUND( (LN(1/0.05) / exposure)*10000 , 6)
       ELSE ROUND( ( ((k_count+1) * POWER(1 - 1.0/(9*(k_count+1)) + 1.96/(3*SQRT(k_count+1)), 3)) / exposure )*10000 , 6) END;
$$;

CREATE OR REPLACE FUNCTION kpi_rate_ratio_ci(k_pre NUMERIC, exp_pre NUMERIC, k_pos NUMERIC, exp_pos NUMERIC)
RETURNS TABLE (rr NUMERIC, lcl NUMERIC, ucl NUMERIC, z NUMERIC)
LANGUAGE sql AS $$
WITH prep AS (
  SELECT GREATEST(k_pre,0)::numeric  AS k0,
         GREATEST(k_pos,0)::numeric  AS k1,
         NULLIF(exp_pre,0)::numeric  AS e0,
         NULLIF(exp_pos,0)::numeric  AS e1
),
adj AS (
  SELECT (CASE WHEN k0=0 OR k1=0 THEN k0+0.5 ELSE k0 END)::numeric AS k0a,
         (CASE WHEN k0=0 OR k1=0 THEN k1+0.5 ELSE k1 END)::numeric AS k1a,
         (CASE WHEN k0=0 OR k1=0 THEN e0+0.5 ELSE e0 END)::numeric AS e0a,
         (CASE WHEN k0=0 OR k1=0 THEN e1+0.5 ELSE e1 END)::numeric AS e1a
  FROM prep
)
SELECT
  CASE WHEN e0a IS NULL OR e1a IS NULL THEN NULL
       WHEN k0a=0 AND k1a=0 THEN NULL
       ELSE ROUND( ( (k1a/e1a) / (k0a/e0a) )::numeric, 6) END,
  CASE WHEN e0a IS NULL OR e1a IS NULL OR (k0a=0 AND k1a=0) THEN NULL
       ELSE ROUND( EXP( LN( (k1a/e1a) / (k0a/e0a) ) - 1.96*SQRT(1/k0a + 1/k1a) ) , 6) END,
  CASE WHEN e0a IS NULL OR e1a IS NULL OR (k0a=0 AND k1a=0) THEN NULL
       ELSE ROUND( EXP( LN( (k1a/e1a) / (k0a/e0a) ) + 1.96*SQRT(1/k0a + 1/k1a) ) , 6) END,
  CASE WHEN e0a IS NULL OR e1a IS NULL OR (k0a=0 AND k1a=0) THEN NULL
       ELSE ROUND( LN( (k1a/e1a) / (k0a/e0a) ) / SQRT(1/k0a + 1/k1a) , 6) END
FROM adj;
$$;

-- BA compact view (uses functions above)
CREATE OR REPLACE VIEW kpi_ba_sr_tah AS
WITH p AS (SELECT 30::int AS win),
act AS (SELECT a.action_id, a.airport_id, a.location_id, a.date_utc::date AS d FROM wildlife.fact_control_action a),
win AS (
  SELECT action_id, airport_id, location_id, d,
         (d - (SELECT win FROM p) * INTERVAL '1 day')::date AS pre_ini,
         (d - INTERVAL '1 day')::date                      AS pre_fim,
         d                                                 AS pos_ini,
         (d + (SELECT win FROM p) * INTERVAL '1 day')::date AS pos_fim
  FROM act
),
mov_pre AS (
  SELECT w.action_id, COALESCE(SUM(m.movements),0)::numeric AS exp_pre
  FROM win w LEFT JOIN v_movements_daily m ON m.airport_id=w.airport_id AND m.day BETWEEN w.pre_ini AND w.pre_fim
  GROUP BY w.action_id
),
mov_pos AS (
  SELECT w.action_id, COALESCE(SUM(m.movements),0)::numeric AS exp_pos
  FROM win w LEFT JOIN v_movements_daily m ON m.airport_id=w.airport_id AND m.day BETWEEN w.pos_ini AND w.pos_fim
  GROUP BY w.action_id
),
str_pre AS (
  SELECT w.action_id, COUNT(*)::numeric AS k_pre
  FROM win w JOIN wildlife.fact_strike s ON s.airport_id=w.airport_id AND s.location_id=w.location_id
   AND s.date_utc BETWEEN w.pre_ini AND w.pre_fim
  GROUP BY w.action_id
),
str_pos AS (
  SELECT w.action_id, COUNT(*)::numeric AS k_pos
  FROM win w JOIN wildlife.fact_strike s ON s.airport_id=w.airport_id AND s.location_id=w.location_id
   AND s.date_utc BETWEEN w.pos_ini AND w.pos_fim
  GROUP BY w.action_id
),
av_pre AS (
  SELECT w.action_id, COALESCE(SUM(v.si_cnt),0)::numeric AS av_pre, COALESCE(SUM(v.horas),0)::numeric AS horas_pre
  FROM win w LEFT JOIN (
    SELECT s.airport_id, s.location_id, s.date_utc, COUNT(si.sighting_item_id)::numeric AS si_cnt, COALESCE(MAX(s.effort_hours),0)::numeric AS horas
    FROM wildlife.fact_sighting s LEFT JOIN wildlife.fact_sighting_item si ON si.sighting_id=s.sighting_id
    GROUP BY s.airport_id, s.location_id, s.date_utc
  ) v ON v.airport_id=w.airport_id AND v.location_id=w.location_id AND v.date_utc BETWEEN w.pre_ini AND w.pre_fim
  GROUP BY w.action_id
),
av_pos AS (
  SELECT w.action_id, COALESCE(SUM(v.si_cnt),0)::numeric AS av_pos, COALESCE(SUM(v.horas),0)::numeric AS horas_pos
  FROM win w LEFT JOIN (
    SELECT s.airport_id, s.location_id, s.date_utc, COUNT(si.sighting_item_id)::numeric AS si_cnt, COALESCE(MAX(s.effort_hours),0)::numeric AS horas
    FROM wildlife.fact_sighting s LEFT JOIN wildlife.fact_sighting_item si ON si.sighting_id=s.sighting_id
    GROUP BY s.airport_id, s.location_id, s.date_utc
  ) v ON v.airport_id=w.airport_id AND v.location_id=w.location_id AND v.date_utc BETWEEN w.pos_ini AND w.pos_fim
  GROUP BY w.action_id
)
SELECT w.*,
       mpre.exp_pre, mpos.exp_pos,
       spre.k_pre, spos.k_pos,
       (SELECT sr10k  FROM kpi_sr10k_byar(spre.k_pre, mpre.exp_pre))  AS sr10k_pre,
       (SELECT lcl10k FROM kpi_sr10k_byar(spre.k_pre, mpre.exp_pre)) AS lcl_pre,
       (SELECT ucl10k FROM kpi_sr10k_byar(spre.k_pre, mpre.exp_pre)) AS ucl_pre,
       (SELECT sr10k  FROM kpi_sr10k_byar(spos.k_pos, mpos.exp_pos))  AS sr10k_pos,
       (SELECT lcl10k FROM kpi_sr10k_byar(spos.k_pos, mpos.exp_pos)) AS lcl_pos,
       (SELECT ucl10k FROM kpi_sr10k_byar(spos.k_pos, mpos.exp_pos)) AS ucl_pos,
       (SELECT rr    FROM kpi_rate_ratio_ci(spre.k_pre, mpre.exp_pre, spos.k_pos, mpos.exp_pos)) AS rr,
       (SELECT lcl   FROM kpi_rate_ratio_ci(spre.k_pre, mpre.exp_pre, spos.k_pos, mpos.exp_pos)) AS rr_lcl,
       (SELECT ucl   FROM kpi_rate_ratio_ci(spre.k_pre, mpre.exp_pre, spos.k_pos, mpos.exp_pos)) AS rr_ucl,
       (SELECT z     FROM kpi_rate_ratio_ci(spre.k_pre, mpre.exp_pre, spos.k_pos, mpos.exp_pos)) AS rr_z,
       apre.av_pre, apre.horas_pre, CASE WHEN apre.horas_pre>0 THEN ROUND(apre.av_pre/apre.horas_pre,6) END AS tah_pre,
       apos.av_pos, apos.horas_pos, CASE WHEN apos.horas_pos>0 THEN ROUND(apos.av_pos/apos.horas_pos,6) END AS tah_pos
FROM win w
LEFT JOIN mov_pre mpre ON mpre.action_id=w.action_id
LEFT JOIN mov_pos mpos ON mpos.action_id=w.action_id
LEFT JOIN str_pre spre  ON spre.action_id=w.action_id
LEFT JOIN str_pos spos  ON spos.action_id=w.action_id
LEFT JOIN av_pre  apre  ON apre.action_id=w.action_id
LEFT JOIN av_pos  apos  ON apos.action_id=w.action_id;

-- DiD function
CREATE OR REPLACE FUNCTION kpi_did_sr10k(p_action_id BIGINT, p_control_locations BIGINT[], p_window_days INTEGER DEFAULT 30)
RETURNS TABLE (action_id BIGINT, airport_id BIGINT, treat_location_id BIGINT, dt_acao DATE, sr_pre_treat NUMERIC, sr_pos_treat NUMERIC, sr_pre_ctrl NUMERIC, sr_pos_ctrl NUMERIC, did NUMERIC)
LANGUAGE sql AS $$
WITH act AS (SELECT a.action_id, a.airport_id, a.location_id AS loc_t, a.date_utc::date AS d FROM wildlife.fact_control_action a WHERE a.action_id=p_action_id),
win AS (
  SELECT action_id, airport_id, loc_t, d,
         (d - (p_window_days||' days')::interval)::date AS pre_ini,
         (d - interval '1 day')::date                   AS pre_fim,
         d                                              AS pos_ini,
         (d + (p_window_days||' days')::interval)::date AS pos_fim
  FROM act
),
exp_pre AS (
  SELECT w.action_id, COALESCE(SUM(m.movements),0)::numeric AS e_pre
  FROM win w LEFT JOIN v_movements_daily m ON m.airport_id=w.airport_id AND m.day BETWEEN w.pre_ini AND w.pre_fim
  GROUP BY w.action_id
),
exp_pos AS (
  SELECT w.action_id, COALESCE(SUM(m.movements),0)::numeric AS e_pos
  FROM win w LEFT JOIN v_movements_daily m ON m.airport_id=w.airport_id AND m.day BETWEEN w.pos_ini AND w.pos_fim
  GROUP BY w.action_id
),
k_pre_t AS (
  SELECT w.action_id, COUNT(*)::numeric AS k
  FROM win w JOIN wildlife.fact_strike s ON s.airport_id=w.airport_id AND s.location_id=w.loc_t AND s.date_utc BETWEEN w.pre_ini AND w.pre_fim
  GROUP BY w.action_id
),
k_pos_t AS (
  SELECT w.action_id, COUNT(*)::numeric AS k
  FROM win w JOIN wildlife.fact_strike s ON s.airport_id=w.airport_id AND s.location_id=w.loc_t AND s.date_utc BETWEEN w.pos_ini AND w.pos_fim
  GROUP BY w.action_id
),
k_pre_c AS (
  SELECT w.action_id, COUNT(*)::numeric AS k
  FROM win w JOIN wildlife.fact_strike s ON s.airport_id=w.airport_id AND s.location_id = ANY(p_control_locations) AND s.date_utc BETWEEN w.pre_ini AND w.pre_fim
  GROUP BY w.action_id
),
k_pos_c AS (
  SELECT w.action_id, COUNT(*)::numeric AS k
  FROM win w JOIN wildlife.fact_strike s ON s.airport_id=w.airport_id AND s.location_id = ANY(p_control_locations) AND s.date_utc BETWEEN w.pos_ini AND w.pos_fim
  GROUP BY w.action_id
)
SELECT w.action_id, w.airport_id, w.loc_t AS treat_location_id, w.d AS dt_acao,
       (SELECT (k/e)*10000 FROM k_pre_t kt JOIN exp_pre e USING (action_id)) AS sr_pre_treat,
       (SELECT (k/e)*10000 FROM k_pos_t kt JOIN exp_pos e USING (action_id)) AS sr_pos_treat,
       (SELECT (k/e)*10000 FROM k_pre_c kc JOIN exp_pre e USING (action_id)) AS sr_pre_ctrl,
       (SELECT (k/e)*10000 FROM k_pos_c kc JOIN exp_pos e USING (action_id)) AS sr_pos_ctrl,
       ((SELECT (k/e)*10000 FROM k_pos_t kt JOIN exp_pos e USING (action_id))
       - (SELECT (k/e)*10000 FROM k_pre_t kt JOIN exp_pre e USING (action_id))
       - ((SELECT (k/e)*10000 FROM k_pos_c kc JOIN exp_pos e USING (action_id)) - (SELECT (k/e)*10000 FROM k_pre_c kc JOIN exp_pre e USING (action_id)))) AS did
FROM win w;
$$;

-- Spatial BA
UPDATE wildlife.fact_control_action
SET geom = COALESCE(geom, ST_SetSRID(ST_MakePoint(longitude_dec, latitude_dec), 4326))
WHERE latitude_dec IS NOT NULL AND longitude_dec IS NOT NULL;

UPDATE wildlife.fact_strike
SET geom = COALESCE(geom, ST_SetSRID(ST_MakePoint(longitude_dec, latitude_dec), 4326))
WHERE latitude_dec IS NOT NULL AND longitude_dec IS NOT NULL;

UPDATE wildlife.fact_sighting
SET geom = COALESCE(geom, ST_SetSRID(ST_MakePoint(longitude_dec, latitude_dec), 4326))
WHERE latitude_dec IS NOT NULL AND longitude_dec IS NOT NULL;

CREATE OR REPLACE FUNCTION kpi_ba_spatial(p_action_id BIGINT, p_radius_m NUMERIC, p_window_days INTEGER DEFAULT 30)
RETURNS TABLE (
  action_id BIGINT, airport_id BIGINT, dt_acao DATE,
  radius_m NUMERIC, pre_ini DATE, pre_fim DATE, pos_ini DATE, pos_fim DATE,
  exp_pre NUMERIC, exp_pos NUMERIC, k_pre NUMERIC,  k_pos NUMERIC,
  sr10k_pre NUMERIC, lcl_pre NUMERIC, ucl_pre NUMERIC,
  sr10k_pos NUMERIC, lcl_pos NUMERIC, ucl_pos NUMERIC,
  rr NUMERIC, rr_lcl NUMERIC, rr_ucl NUMERIC, rr_z NUMERIC,
  tah_pre NUMERIC, tah_pos NUMERIC
) LANGUAGE sql AS $$
WITH act AS (SELECT a.action_id, a.airport_id, a.date_utc::date AS d, a.geom FROM wildlife.fact_control_action a WHERE a.action_id=p_action_id AND a.geom IS NOT NULL),
win AS (
  SELECT action_id, airport_id, d,
         (d - (p_window_days||' days')::interval)::date AS pre_ini,
         (d - interval '1 day')::date                   AS pre_fim,
         d                                              AS pos_ini,
         (d + (p_window_days||' days')::interval)::date AS pos_fim
  FROM act
),
buf AS (SELECT action_id, airport_id, d, ST_Transform(geom,3857) AS g_3857 FROM act),
ring AS (SELECT action_id, airport_id, d, ST_Buffer(g_3857, p_radius_m)::geometry AS gbuf FROM buf),
k_pre AS (
  SELECT w.action_id, COUNT(*)::numeric AS k
  FROM win w JOIN ring r USING (action_id, airport_id, d)
  JOIN wildlife.fact_strike s ON s.airport_id=w.airport_id AND s.date_utc BETWEEN w.pre_ini AND w.pre_fim AND s.geom IS NOT NULL
   AND ST_Intersects(ST_Transform(s.geom,3857), r.gbuf)
  GROUP BY w.action_id
),
k_pos AS (
  SELECT w.action_id, COUNT(*)::numeric AS k
  FROM win w JOIN ring r USING (action_id, airport_id, d)
  JOIN wildlife.fact_strike s ON s.airport_id=w.airport_id AND s.date_utc BETWEEN w.pos_ini AND w.pos_fim AND s.geom IS NOT NULL
   AND ST_Intersects(ST_Transform(s.geom,3857), r.gbuf)
  GROUP BY w.action_id
),
av_pre AS (
  SELECT w.action_id, COALESCE(SUM(v.si_cnt),0)::numeric AS itens, COALESCE(SUM(v.horas),0)::numeric AS horas
  FROM win w JOIN ring r USING (action_id, airport_id, d)
  LEFT JOIN (
    SELECT s.airport_id, s.date_utc, COUNT(si.sighting_item_id)::numeric AS si_cnt, COALESCE(MAX(s.effort_hours),0)::numeric AS horas, s.geom
    FROM wildlife.fact_sighting s LEFT JOIN wildlife.fact_sighting_item si ON si.sighting_id=s.sighting_id
    GROUP BY s.airport_id, s.date_utc, s.geom
  ) v ON v.airport_id=w.airport_id AND v.date_utc BETWEEN w.pre_ini AND w.pre_fim AND v.geom IS NOT NULL
     AND ST_Intersects(ST_Transform(v.geom,3857), r.gbuf)
  GROUP BY w.action_id
),
av_pos AS (
  SELECT w.action_id, COALESCE(SUM(v.si_cnt),0)::numeric AS itens, COALESCE(SUM(v.horas),0)::numeric AS horas
  FROM win w JOIN ring r USING (action_id, airport_id, d)
  LEFT JOIN (
    SELECT s.airport_id, s.date_utc, COUNT(si.sighting_item_id)::numeric AS si_cnt, COALESCE(MAX(s.effort_hours),0)::numeric AS horas, s.geom
    FROM wildlife.fact_sighting s LEFT JOIN wildlife.fact_sighting_item si ON si.sighting_id=s.sighting_id
    GROUP BY s.airport_id, s.date_utc, s.geom
  ) v ON v.airport_id=w.airport_id AND v.date_utc BETWEEN w.pos_ini AND w.pos_fim AND v.geom IS NOT NULL
     AND ST_Intersects(ST_Transform(v.geom,3857), r.gbuf)
  GROUP BY w.action_id
),
exp_pre AS (
  SELECT w.action_id, COALESCE(SUM(m.movements),0)::numeric AS e
  FROM win w LEFT JOIN v_movements_daily m ON m.airport_id=w.airport_id AND m.day BETWEEN w.pre_ini AND w.pre_fim
  GROUP BY w.action_id
),
exp_pos AS (
  SELECT w.action_id, COALESCE(SUM(m.movements),0)::numeric AS e
  FROM win w LEFT JOIN v_movements_daily m ON m.airport_id=w.airport_id AND m.day BETWEEN w.pos_ini AND w.pos_fim
  GROUP BY w.action_id
)
SELECT w.action_id, w.airport_id, w.d AS dt_acao, p_radius_m AS radius_m,
       w.pre_ini, w.pre_fim, w.pos_ini, w.pos_fim,
       epre.e AS exp_pre, epos.e AS exp_pos,
       COALESCE(kp.k,0) AS k_pre, COALESCE(ks.k,0) AS k_pos,
       (SELECT sr10k  FROM kpi_sr10k_byar(COALESCE(kp.k,0), epre.e)) AS sr10k_pre,
       (SELECT lcl10k FROM kpi_sr10k_byar(COALESCE(kp.k,0), epre.e)) AS lcl_pre,
       (SELECT ucl10k FROM kpi_sr10k_byar(COALESCE(kp.k,0), epre.e)) AS ucl_pre,
       (SELECT sr10k  FROM kpi_sr10k_byar(COALESCE(ks.k,0), epos.e)) AS sr10k_pos,
       (SELECT lcl10k FROM kpi_sr10k_byar(COALESCE(ks.k,0), epos.e)) AS lcl_pos,
       (SELECT ucl10k FROM kpi_sr10k_byar(COALESCE(ks.k,0), epos.e)) AS ucl_pos,
       (SELECT rr    FROM kpi_rate_ratio_ci(COALESCE(kp.k,0), epre.e, COALESCE(ks.k,0), epos.e)) AS rr,
       (SELECT lcl   FROM kpi_rate_ratio_ci(COALESCE(kp.k,0), epre.e, COALESCE(ks.k,0), epos.e)) AS rr_lcl,
       (SELECT ucl   FROM kpi_rate_ratio_ci(COALESCE(kp.k,0), epre.e, COALESCE(ks.k,0), epos.e)) AS rr_ucl,
       (SELECT z     FROM kpi_rate_ratio_ci(COALESCE(kp.k,0), epre.e, COALESCE(ks.k,0), epos.e)) AS rr_z,
       CASE WHEN apre.horas>0 THEN ROUND(apre.itens/apre.horas,6) END AS tah_pre,
       CASE WHEN apos.horas>0 THEN ROUND(apos.itens/apos.horas,6) END AS tah_pos
FROM win w
LEFT JOIN k_pre kp  ON kp.action_id=w.action_id
LEFT JOIN k_pos ks  ON ks.action_id=w.action_id
LEFT JOIN av_pre apre ON apre.action_id=w.action_id
LEFT JOIN av_pos apos ON apos.action_id=w.action_id
LEFT JOIN exp_pre epre ON epre.action_id=w.action_id
LEFT JOIN exp_pos epos ON epos.action_id=w.action_id;
$$;

-- End of package
